source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'GoogleCastPodFail_Example', :exclusive => true do
  pod "GoogleCastPodFail", :path => "../"
end

target 'GoogleCastPodFail_Tests', :exclusive => true do
  pod "GoogleCastPodFail", :path => "../"

  
end
